name: Auto Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    container:
      image: archlinux:latest
      
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel rust git gtk4 gtk4-layer-shell pkgconf
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Fix git permissions
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      
      - name: Build project
        run: cargo build --release
          
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          generate_release_notes: true
          files: target/release/pulsar
